### ISSUE TITLE
Fully annotate and document public operations

### ISSUE THREAD

**Issue by forman** [CCI-Tools/ect-core#22]
Make sure all public ECT operations are tagged, have type annotations and comprehensive usage and background information and clear input/output descriptions.

Verify by listing all operations by

    ect op list

and then printing information like so

    ect op info OP

- [x] coregister
- [x] pearson_correlation
- [x] harmonize
- [x] open_dataset
- [x] read_json
- [x] read_netcdf
- [x] read_object
- [x] read_text
- [x] save_dataset
- [x] write_json
- [x] write_netcdf3
- [x] write_netcdf4
- [x] write_object
- [x] write_text
- [x] plot_map
- [x] select_var
- [x] subset_spatial
- [x] subset_temporal
- [x] subset_temporal_index
- [x] timeseries
- [x] timeseries_mean

**Comment by JanisGailis** [comment]
- [ ] coregister
- [ ] pearson_correlation
- [ ] harmonize
- [ ] open_dataset
- [ ] read_json
- [ ] read_netcdf
- [ ] read_object
- [ ] read_text
- [ ] save_dataset
- [ ] write_json
- [ ] write_netcdf3
- [ ] write_netcdf4
- [ ] write_object
- [ ] write_text
- [ ] plot_map
- [ ] select_variables
- [ ] subset_spatial
- [ ] subset_temporal
- [ ] subset_temporal_index
- [ ] timeseries
- [ ] timeseries_mean
