### ISSUE TITLE
Harmonize operation names, their parameters and return values 

### ISSUE THREAD

**Issue by forman** [CCI-Tools/ect-core#35]
The names of ECT operations shall be catchy and generally understandable. Ideally, we would only use verbs because every operation *does* something with its inputs and returns a the result of the operation , which is ideally a *pure function*. 

Different ECT operations that have a parameter for a similar purpose should all use the same parameter name, same data type, and same description, and ideally use the same argument position. 

Examples:

* If an operation transforms a `xarray.Dataset` it should always be the first parameter and should always be called `ds`.  Other parameters of type  `xarray.Dataset` should have names using a `ds_` prefix.
* Operations which have a parameter that selects variables from a given dataset, it may be called `var` and its value may be either `None`, a `str`, or a sequence of `str`. Other rules may apply, e.g. a `str`may contain comma-separated names or use wildcards ect., that's fine, but this shall apply to all the operations that have the `var` parameter. 
* Operations which have a parameter that identifies a file to read from or write to, it may be called `file` and its value may be either `None`, a `str` (= file path), or Python file object. 

- [x] coregister
- [x] pearson_correlation
- [x] harmonize
- [x] open_dataset
- [x] read_json
- [x] read_netcdf
- [x] read_object
- [x] read_text
- [x] save_dataset
- [x] write_json
- [x] write_netcdf3
- [x] write_netcdf4
- [x] write_object
- [x] write_text
- [x] plot_map
- [x] select_var
- [x] subset_spatial
- [x] subset_temporal
- [x] subset_temporal_index
- [x] timeseries
- [x] timeseries_mean

**Comment by forman** [comment]
Hi Janis, this example should better explain what I was talking about (find `to_list()` proto in `ect.core.util`):

    def some_op(ds: xr.Dataset, var: Union[None, str, List[str]] = None, ...):
        var_names = to_list(var) 

        for var_name in var_names:
            ...

**Comment by JanisGailis** [comment]
Can't use
```python
    def some_op(ds: xr.Dataset, var: Union[None, str, List[str]] = None, ...):


until #46 has not been solved.
