### ISSUE TITLE
No data sources found

### ISSUE THREAD

**Issue by JanisGailis** [CCI-Tools/ect-core#38]
What happened?

![no_data_sources](https://cloud.githubusercontent.com/assets/9655353/18794677/f65b94bc-81c0-11e6-91c4-81a7ff18749d.png)

**Comment by forman** [comment]
It seems the `ect.ds` plugin is not activated. You may try reinstalling ECT:

     python setup.py develop

**Comment by JanisGailis** [comment]
Yes, that was exactly the previous command in the screenshot. Is it working
for you normally?

**Comment by forman** [comment]
Closed in favour of #40, because this seems no longer an ECT problem.
