### ISSUE TITLE
ESA CCI ODP service at CEDA is empty

### ISSUE THREAD

**Issue by forman** [CCI-Tools/ect-core#40]
Suddenly

    $ ect ds list
    No data sources found

See #38. Quick investigation showed that the index of the [ESA CCI ODP service at CEDA](https://esgf-index1.ceda.ac.uk/search/esacci-ceda/) seems empty, datasets can no longer be queried. 

This definitely blocks the ECT release.

**Comment by forman** [comment]
ODP Team says: "We are in the process of republishing the data through the ESGF system so there will be a period when the datasets are not available."

**Comment by JanisGailis** [comment]
Now it seems populated again.

**Comment by lkeupp** [comment]
when I try, it still returns: `No data sources found`

**Comment by forman** [comment]
Data is back.
