### ISSUE TITLE
Allow opening dataset comprising multiple local files

### ISSUE THREAD

**Issue by forman** [CCI-Tools/ect-core#42]
Currently `ect res open` allows for opening datasets from a registered *data store* only. It should also allow for accessing a dataset comprising multiple local files. Alternatively, we could also introduce an additional command, say `ect res mfopen` (multi-file open).

Another idea is to add a new data source globally to ECT, in order to make it permanently available:

    ect ds add [-r, --recursive] DS_NAME FILE_OR_DIR...

The new data source DS_NAME can then be used like any other (remote) data source. `FILE_OR_DIR...` is a list of file names and/or directory names which may include wildcards (on Windows).

This issue is a blocker as long as issue #40 is not solved.

**Comment by lkeupp** [comment]
This is really important from the user point of view.
Do I understnad the proposed options/examples correctly: with `ect res mfopen` the user would be able to choose a local data source (directory+file name) directly to add it to the current workspace (one time use), while `ect ds add ` would establish a permanent alias for the data source?
