### ISSUE TITLE
Unions can not be used with isinstance

### ISSUE THREAD

**Issue by JanisGailis** [CCI-Tools/ect-core#45]
```bash
(ect_env)ccitbx@ccitbx-VirtualBox:~/Development/ect-core$ ect res set cc_tot ect.ops.select.select_var ds=cl07 var=cc_total
Using FSWorkspaceManager
ect res: error: Unions cannot be used with isinstance().
```
Apparently ect res does not like my new select_var implementation with
```python
var: Union[None, str, List[str]] = None

**Comment by JanisGailis** [comment]
Guido himself did it:
https://mail.python.org/pipermail/python-checkins/2015-June/136736.html

**Comment by forman** [comment]
I do not consider this being a blocker. Just remove the type annotation from the function for time being and create a new issue saying that we need type validation that can understand Python "types" created with the `typing` package.

**Comment by JanisGailis** [comment]
Thanks! Yes, *blocker* was a bit too strong.
