### ISSUE TITLE
How to properly handle datetime in operations?

### ISSUE THREAD

**Issue by JanisGailis** [CCI-Tools/ect-core#47]
Having an operation that expects to get string formatted datetime, such as '2007-30-10', the cli interface apparently translates that to an int and complains about it.

Any ideas how to solve this?

![expected_str_got_int](https://cloud.githubusercontent.com/assets/9655353/18875950/1cf431ce-84c8-11e6-9ac2-144fea7e2977.png)

**Comment by forman** [comment]
Grrr! Oh dear, yes, it computes `2007-30-10 = 1967`

**Comment by forman** [comment]
Users will have to use quotes, i.e. `time_min='2007-30-10'`
I agree, this is not nice, but that's how it is for time being!

**Comment by JanisGailis** [comment]
![kind_of_works](https://cloud.githubusercontent.com/assets/9655353/18881855/40dc039a-84dd-11e6-9556-3ca5f9fbca6c.png)

On Linux (bash, to be more precise) the only way this works is if the quote character is escaped, as such:

```bash
time_min=\'2007-10-10\'
```

I'll update the operation info. The interesting part is that 

```bash
ect res open ... ... 2007-01-01 2007-12-30
```

works without quotes or anything. I presume the command line is parsed in a different way there.

Anyway, closing for now.
