### ISSUE TITLE
Pearson correlation pixel by pixel correlation

### ISSUE THREAD

**Issue by JanisGailis** [CCI-Tools/ect-core#56]
It should be possible to calculate Pearson correlation on pixel by pixel basis on time/lat/lon datasets

**Comment by JanisGailis** [comment]
Done.

**Comment by cpaulik** [comment]
You might be interested in an recursive implementation of the pearson correlation coefficient. E.g. https://github.com/TUW-GEO/pytesmo/blob/master/pytesmo/metrics.py#L410 to speed things up. You could do it time slice by time slice instead of reading each timeseries using `isel`
