### ISSUE TITLE
Temporal subset should be able to recognize time in Julian days

### ISSUE THREAD

**Issue by JanisGailis** [CCI-Tools/ect-core#60]
Currently temporal subset works only with datetime strings. There are other widely used CF compliant time formats, such as time in Julian days, which is used in the clouds CCI. Operations should be able to work with this as well.

**Comment by mzuehlke** [comment]
This applies to the following dataset:
`esacci.CLOUD.mon.L3C.CLD_PRODUCTS.AVHRR.NOAA-15.AVHRR_NOAA.1-0.r1`
The time variable is defined in the following way and not correctly interpreted by xarray:
```
<xarray.DataArray 'time' (time: 12)>
array([ 2454101.5,  2454132.5,  2454160.5,  2454191.5,  2454221.5,
        2454252.5,  2454282.5,  2454313.5,  2454344.5,  2454374.5,
        2454405.5,  2454435.5])
Coordinates:
  * time     (time) float64 2.454e+06 2.454e+06 2.454e+06 2.454e+06 ...
Attributes:
    long_name: time in julian days
    calendar: julian
    units: day
    standard_name: time
```

**Comment by JanisGailis** [comment]
Done.
