### ISSUE TITLE
Commands executed by WebAPI shall report progress

### ISSUE THREAD

**Issue by forman** [CCI-Tools/ect-core#61]
Currently, none of the commands executed by the WebAPI service report progress back to the caller. This is a blocker, because our users will have no clue what the tool is currently doing, e.g. when obtaining or computing a workspace resource (i.e. fetch data from ESA ODP). To them, it looks like the ECT tool hangs.  

A clean solution is to make all WebAPI commands return a monitor handle immediately, so that we then can poll for monitor state `/ws/monitor_state/{{monitor_id}}` (see also #51). Another implementation option is to use [WebSockets](http://www.tornadoweb.org/en/stable/websocket.html) for those commands usually taking considerable time to execute.

For time being, and for use via the CLI, we could use a `ConsoleMonitor` in the WebAPI implementation code, which displays progress on the terminal while the CLI is blocked by the WebAPI service's command execution.

**Comment by lkeupp** [comment]
Yes, that's important for the user
